name: Release Distributables

on:
  release:
    types:
      - published

jobs:
  build-n-upload:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set package version
      run: |
        sed -i 's\0.0.0\${{ github.event.release.name }}\g' setup.cfg
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: python -m build
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --repository testpypi --non-interactive dist/*

